### ISSUE TITLE
PerkLight? More like PerkDark amirite?

### ISSUE THREAD

**Issue by joshuakitchen** [Toumari/PerkLight#10]
There's no light theme, the dark theme is affecting my vision, i'm trying to train my eyes to look at the sun, could you please create a light theme?

![Alt Text](https://media.giphy.com/media/IgY3Zh0EMX3xLZ484q/giphy.gif)

**Comment by Toumari** [comment]
Hi Josh,

[https://github.com/Toumari/PerkLight/tree/light_theme](url) is in the process of being reviewed and pending successful review should be on the app store shortly.
