### ISSUE TITLE
Ability to re-roll individual perks in addition to rolling all 4

### ISSUE THREAD

**Issue by mattdriver123** [Toumari/PerkLight#18]
As a user I'd like to be able to:
- tap on an individual perk to re-roll just that perk

**Comment by joshuakitchen** [comment]
This enhancement looks good.

![Alt Text](https://media.giphy.com/media/ifRVs1bLE0Lf1LKPMl/giphy.gif)

**Comment by deibuji** [comment]
Implemented feature in #31
