### ISSUE TITLE
Ability to view the description of the perks

### ISSUE THREAD

**Issue by mattdriver123** [Toumari/PerkLight#19]
As a user I'd like to be able to:
- read the descriptions of individual perks

**Comment by joshuakitchen** [comment]
This enhancement looks good.

![Alt Text](https://media.giphy.com/media/ifRVs1bLE0Lf1LKPMl/giphy.gif)

**Comment by mattdriver123** [comment]
First version of perk descriptions is complete and will be available in the next release 1.0.0+11.
Perk descriptions can be viewed by tapping once on the randomised perks, or by tapping on the perk icon next to the perk name in the "Perk Configuration" page.
