### ISSUE TITLE
Cannot generate random builds

### ISSUE THREAD

**Issue by joshuakitchen** [Toumari/PerkLight#5]
Within the development branch, i'm unable to generate random builds.

Something about length on an object?

![Alt Text](https://media.giphy.com/media/ifRVs1bLE0Lf1LKPMl/giphy.gif)

**Comment by joshuakitchen** [comment]
It's been an hour and this hasn't been fixed, can you fix @Toumari please?

I believe @adamckay is also waiting on this.

**Comment by joshuakitchen** [comment]
This left a mark.

**Comment by joshuakitchen** [comment]
(By the way, it's me, Josh.)

**Comment by Toumari** [comment]
Fake News.
